// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdrgZSOyIaMTJVuwXHsqZz7hNHf-5Xev4',
    appId: '1:599559124740:web:933d2a4faace495532c251',
    messagingSenderId: '599559124740',
    projectId: 'yollr-e70fa',
    authDomain: 'yollr-e70fa.firebaseapp.com',
    storageBucket: 'yollr-e70fa.firebasestorage.app',
    measurementId: 'G-3K51FJSCM7',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8LwTOb6vyWcCr22ShY7YjnvpxOc2nL3w',
    appId: '1:599559124740:ios:45c73a27a3267ecb32c251',
    messagingSenderId: '599559124740',
    projectId: 'yollr-e70fa',
    storageBucket: 'yollr-e70fa.firebasestorage.app',
    iosBundleId: 'com.example.yollrAdminPanel',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk1ZxojgYExdpunalcT1Cyh2E6MCMo18Q',
    appId: '1:599559124740:android:2cc88322bc19af4d32c251',
    messagingSenderId: '599559124740',
    projectId: 'yollr-e70fa',
    storageBucket: 'yollr-e70fa.firebasestorage.app',
  );

}